apiVersion: v1
kind: Service
metadata:
  name: {{ CI_COMMIT_REF_NAME }}-webapp-svc
spec:
  selector:
    app: {{ CI_COMMIT_REF_NAME }}-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
